# Generated by Django 4.1.1 on 2022-09-26 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drones',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('[0-9]')]),
        ),
    ]
