# Generated by Django 4.1.1 on 2022-09-26 03:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_alter_drones_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drones',
            name='name',
        ),
        migrations.AddField(
            model_name='drones',
            name='battery',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='drones',
            name='model',
            field=models.CharField(choices=[('lightweight', 'Lightweight'), ('middleweight', 'Middleweight'), ('cruiserweight', 'Cruiserweight'), ('heavyweight', 'Heavyweight')], default='lightweight', max_length=32),
        ),
        migrations.AddField(
            model_name='drones',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='drones',
            name='state',
            field=models.CharField(choices=[('idle', 'IDLE'), ('loading', 'LOADING'), ('loaded', 'LOADED'), ('delivering', 'DELIVERING'), ('delivered', 'DELIVERED'), ('returning', 'RETURNING')], default='idle', max_length=32),
        ),
        migrations.AddField(
            model_name='drones',
            name='weight',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(500)]),
        ),
    ]
