# Generated by Django 4.1.1 on 2022-09-26 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_remove_drones_name_drones_battery_drones_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('[0-9a-zA-Z_-]', 'Only letters, numbers, and underscores are allowed')])),
                ('weight', models.IntegerField()),
                ('code', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('[0-9A-Z_]', 'Only upper-case letters, numbers, and underscore are allowed')])),
            ],
        ),
        migrations.AlterField(
            model_name='drones',
            name='model',
            field=models.CharField(choices=[('lightweight', 'Lightweight'), ('middleweight', 'Middleweight'), ('cruiserweight', 'Cruiserweight'), ('heavyweight', 'Heavyweight')], max_length=32, null=True),
        ),
    ]
