# Generated by Django 4.1.1 on 2022-09-26 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0005_medication_alter_drones_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='drones',
            name='medications',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drones.medication'),
        ),
    ]
