# Generated by Django 4.1.1 on 2022-09-26 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0006_drones_medications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drones',
            name='medications',
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('[0-9a-zA-Z-_]', 'Only letters, numbers, and underscores are allowed')]),
        ),
        migrations.AddField(
            model_name='drones',
            name='medications',
            field=models.ManyToManyField(null=True, to='drones.medication'),
        ),
    ]
