# Generated by Django 4.1.1 on 2022-09-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0007_remove_drones_medications_alter_medication_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='image',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
