# Generated by Django 4.1.1 on 2022-09-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0008_medication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
