# Generated by Django 4.1.1 on 2022-09-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0009_alter_medication_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drones',
            name='medications',
            field=models.ManyToManyField(blank=True, to='drones.medication'),
        ),
    ]
